# Generated by Django 4.1.7 on 2023-04-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaternCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.TextField()),
                ("body", models.TextField()),
                ("babydev", models.TextField()),
                ("symptoms", models.TextField()),
                ("tips", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="sales",
            name="animal",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="treatment",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="user",
        ),
        migrations.RemoveField(
            model_name="symptoms",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="animal",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="doctorphone",
        ),
        migrations.RemoveField(
            model_name="client",
            name="book",
        ),
        migrations.AlterField(
            model_name="client",
            name="clientType",
            field=models.CharField(default="Ordinary", max_length=200),
        ),
        migrations.DeleteModel(
            name="Animal",
        ),
        migrations.DeleteModel(
            name="Disease",
        ),
        migrations.DeleteModel(
            name="Sales",
        ),
        migrations.DeleteModel(
            name="Symptoms",
        ),
        migrations.DeleteModel(
            name="Treatment",
        ),
    ]
